// pub const TkError = error{
//     E_SYS,
//     E_NOCOP,
//     E_NOSPT,
//     E_RSFN,
//     E_RSATR,
//     E_PAR,
//     E_ID,
//     E_CTX,
//     E_MACV,
//     E_OACV,
//     E_ILUSE,
//     E_NOMEM,
//     E_LIMIT,
//     E_OBJ,
//     E_NOEXS,
//     E_QOVR,
//     E_RLWAI,
//     E_TMOUT,
//     E_DLT,
//     E_DISWAI,
//     E_IO,
//     E_NOMDAJ,
//     E_BUSY,
//     E_ABORT,
//     E_RONLY,
// };
pub const TkError = error{
    SystemError,
    CoprocessorDisable,
    UnsupportedFunction,
    ReservedFunctionCodeNumber,
    ReservedAttribute,
    ParameterError,
    IncorrectIdNumber,
    ContextError,
    InaccessibleMemoryOrAccessViolation,
    ObjectAccessViolation,
    IncorrectSystemcallUse,
    InsufficientMemory,
    ExceedSystemLimits,
    IncorrectObjectState,
    ObjectNotExist,
    QueuingOverflow,
    ForciblyReleaseWaitState,
    PollingFailOrTimeout,
    WaitedObjectDeleted,
    ReleaseWaitCausedByWaitDisable,
    IOError,
    NoMedia,
    BusyState,
    Aborted,
    WriteProtected,
};
